ALTER TABLE jam_sessions
ADD COLUMN IF NOT EXISTS instruments_json JSONB,
ADD COLUMN IF NOT EXISTS time_signature VARCHAR(10),
ADD COLUMN IF NOT EXISTS note_resolution VARCHAR(10),
ADD COLUMN IF NOT EXISTS bpm INTEGER; 